blank_issues_enabled: false
contact_links:
  - name: Birdr Community
    url: https://www.facebook.com/groups/birdrcommunity/
    about: Discuss Birdr, ask questions, and share your birding experience with the community.
